### ISSUE TITLE
Publish artifact (as release & maven-central)

### ISSUE THREAD

**Issue by olevitt** [InseeFr/Lunatic-Model#17]
At this moment, people that want to use lunatic-model have to build it themselves and manually include the .jar in their application.  
We should probably :  
* [x] Release built artifacts using github releases so that people can download it instead of rebuilding it themselves. That should include some proper version management  
* [x] Publish the artifact on maven-central so that people can simply include it as a dependency  

Do you agree with that ?  
If so, I will try to find some time to submit a PR

**Comment by laurentC35** [comment]
Hello @olevitt ,

What do you think about this solution for the first item : https://github.com/InseeFr/Lunatic-Model/actions

**Comment by olevitt** [comment]
Looks good to me :+1:

**Comment by nsenave** [comment]
Done thanks to @davdarras 

#107
