### ISSUE TITLE
Version 2.2.13 taged in branch dev-lunatic-v2 is not backwards compatible with version 2.2.10

### ISSUE THREAD

**Issue by nsenave** [InseeFr/Lunatic-Model#71]
As a client of the Lunatic-Model library, it is confusing that a patch breaks backwards compatibility.

(Examples)
- Components have a complex object `LabelType` instead of a String for their `label` attribute
- Classes around the `Table` have changed (`CellsType` and `CellsLines` doesn't exist anymore)

**Comment by ORogel** [comment]
Done !
