### ISSUE TITLE
champ Description (texte d'aide) à ajouter

### ISSUE THREAD

**Issue by ORogel** [InseeFr/Lunatic-Model#81]
Tous les composants, à la racine, là où il y a un label il peut a avoir une description (label obligatoire pour le DSFR notamment)

**Comment by laurentC35** [comment]
Pourrais-tu préciser d'un point de vue métier (comportement attendu par l'utilisateur) ce que ça veut dire ?
La description est qq chose en plus du label, un complément comme les déclaration, autre chose encore ?

**Comment by AnneHuSKa** [comment]
![image](https://user-images.githubusercontent.com/71011059/217295563-62e0d0f2-e9cf-43dc-a90e-c08f825d692b.png)

**Comment by AnneHuSKa** [comment]
Dans cet exemple de @jdirand il s'agit des "Exemple : Marseille"

**Comment by jdirand** [comment]
Une description est en réalité un "texte d'aide" afin que l'utilisateur soit aidé/guidé pour compléter ce qu'on lui demande. 
Par exemple, si on demande la ville, certains entreront un code postal.
Avec un texte d'aide, comme "Exemple: Marseille", ils ne douteront plus.
https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/champ-de-saisie

**Comment by jdirand** [comment]
Il me semble qu'elles sont différentes...Par exemple, une déclaration/consigne pourrait dire " Vous pouvez trouver ces informations sur votre déclaration d'impôt", alors que la description est spécifique au champ de saisie (exemple: entrez votre revenu annuel brut). Quoiqu'on pourrait dire en description "entrez votre revenu annuel brut disponible sur votre feuille d'imposition"...

Dans le cas du recensement, lorsqu'on demande la liste des habitants, le "n'oubliez pas le nom de l'occupant principal, vous même etc" c'est une déclaration, on ne le mettrai pas dans une description...je pense donc qu'il y a une différence..à bien définir

**Comment by nsenave** [comment]
Propriété `"description"` ajoutée au sein des composants dans la PR sur le composant `Question` : 

- https://github.com/InseeFr/Lunatic-Model/pull/212

NB : en l'état on peut mettre une description à la fois sur un composant "Question" et ses sous-composants.
