### ISSUE TITLE
Add "type" attribute for controls

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Lunatic-Model#90]
You can see [here](https://github.com/InseeFr/Lunatic/blob/bf6aab3e644370930ea67877ae0a95e1fbaf7260/src/stories/roundabout/source.json#L107)

We have actually 2 strategies to compute controls :
- controls for roundabout
- other controls

To make difference, we add new attribute "type", it can take only one value actually "roundabout"

**Comment by nsenave** [comment]
Since then, a type for row controls in roster for loop components has been added.

- #250 

https://github.com/InseeFr/Lunatic-Model/releases/tag/3.11.0
